# Generated by Django 5.2.5 on 2025-08-08 10:15

import django.db.models.deletion
import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('dong', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('number', models.CharField(max_length=50)),
                ('running_time', models.CharField(max_length=50)),
                ('place_image', models.ImageField(blank=True, null=True, upload_to=places.models.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_content', models.TextField()),
                ('review_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ai_review', models.TextField(null=True)),
                ('review_image', models.ImageField(blank=True, null=True, upload_to=places.models.image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_title', models.CharField(max_length=50)),
                ('report_reason', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.review')),
            ],
        ),
    ]
