# Generated by Django 5.2.5 on 2025-08-14 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayLines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subway_line', models.CharField(max_length=50)),
                ('subway_station', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
