# Generated by Django 5.2.5 on 2025-08-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_subwaylines_place_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subwaylines',
            old_name='subway_line',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='subwaylines',
            old_name='subway_station',
            new_name='station',
        ),
    ]
