# Generated by Django 5.2.5 on 2025-08-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_cart_remove_place_place_image_place_gplace_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularKeyward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100, unique=True)),
                ('place_name', models.CharField(max_length=50)),
                ('search_count', models.IntegerField(default=0)),
            ],
        ),
    ]
