# Generated by Django 5.2.5 on 2025-08-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_popularkeyward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='place',
        ),
        migrations.RemoveField(
            model_name='report',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='place',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
