# Generated by Django 5.2.5 on 2025-08-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_cartitem_cart_remove_cartitem_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularkeyward',
            name='search_count',
        ),
    ]
