# Generated by Django 5.2.5 on 2025-08-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_popularkeyward_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularkeyward',
            name='click_num',
            field=models.IntegerField(default=0),
        ),
    ]
