# Generated by Django 5.2.5 on 2025-08-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_popularkeyward_click_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularkeyward',
            name='click_num',
            field=models.IntegerField(default=1),
        ),
    ]
