# Generated by Django 5.2.5 on 2025-08-23 01:41

import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_popularkeyward_click_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(db_index=True, default=places.models.gen_short, max_length=16, unique=True)),
                ('params', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=places.models.default_expires)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
