# Generated by Django 5.2.5 on 2025-08-23 03:01

import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_fix_routesnapshot_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesnapshot',
            name='id',
            field=models.CharField(default=places.models.gen_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
