# Generated by Django 5.2.5 on 2025-08-15 07:09

import django.db.models.deletion
import django.utils.timezone
import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPlace',
            fields=[
                ('place', models.OneToOneField(help_text='기존 장소 모델과 연결', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.place')),
                ('shop_name', models.CharField(blank=True, help_text='상점명 (장소명과 다를 수 있음)', max_length=100, null=True)),
                ('shop_image', models.ImageField(blank=True, help_text='위키 전용 장소 대표 이미지', null=True, upload_to=wiki.models.wiki_image_upload_path)),
                ('ai_summation', models.TextField(blank=True, help_text='OpenAI가 생성한 장소 요약', null=True)),
                ('ai_summation_info', models.JSONField(blank=True, default=dict, help_text='AI 요약 생성 시 사용된 메타데이터 (모델, 생성시간 등)')),
                ('basic_information', models.TextField(blank=True, help_text='장소의 기본 정보 (영업시간, 가격대 등)', null=True)),
                ('basic_information_info', models.JSONField(blank=True, default=dict, help_text='기본 정보의 메타데이터 (출처, 업데이트 시간 등)')),
                ('kakao_place_id', models.CharField(blank=True, help_text='카카오 API에서 제공하는 장소 고유 ID', max_length=50, null=True)),
                ('google_place_id', models.CharField(blank=True, help_text='구글 Places API에서 제공하는 장소 고유 ID', max_length=100, null=True)),
                ('average_review_score', models.DecimalField(decimal_places=2, default=0.0, help_text='전체 리뷰의 평균 점수', max_digits=3)),
                ('total_review_count', models.IntegerField(default=0, help_text='전체 리뷰 개수')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='위키 정보 최초 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='위키 정보 마지막 수정 시간')),
                ('ai_summary_updated_at', models.DateTimeField(blank=True, help_text='AI 요약이 마지막으로 생성/수정된 시간', null=True)),
            ],
            options={
                'verbose_name': '위키 장소',
                'verbose_name_plural': '위키 장소들',
                'indexes': [models.Index(fields=['kakao_place_id'], name='wiki_wikipl_kakao_p_99557f_idx'), models.Index(fields=['google_place_id'], name='wiki_wikipl_google__978425_idx')],
            },
        ),
        migrations.CreateModel(
            name='WikiSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(help_text='사용자가 입력한 검색어', max_length=200)),
                ('search_type', models.CharField(choices=[('place_name', '장소명 검색'), ('location_name', '지역명 검색'), ('category', '카테고리 검색'), ('mixed', '복합 검색')], default='mixed', help_text='검색 유형', max_length=20)),
                ('result_count', models.IntegerField(default=0, help_text='검색 결과 개수')),
                ('session_key', models.CharField(blank=True, help_text='검색자 세션 키', max_length=64, null=True)),
                ('search_longitude', models.FloatField(blank=True, help_text='검색 시점의 사용자 위치 경도', null=True)),
                ('search_latitude', models.FloatField(blank=True, help_text='검색 시점의 사용자 위치 위도', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='검색 시간')),
            ],
            options={
                'verbose_name': '위키 검색 기록',
                'verbose_name_plural': '위키 검색 기록들',
                'indexes': [models.Index(fields=['search_query'], name='wiki_wikise_search__bb07bd_idx'), models.Index(fields=['created_at'], name='wiki_wikise_created_3ba919_idx'), models.Index(fields=['session_key'], name='wiki_wikise_session_1ef90e_idx')],
            },
        ),
    ]
