# Generated by Django 5.2.5 on 2025-08-15 07:19

import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiplace',
            name='ai_summation_info',
            field=models.JSONField(blank=True, default=wiki.models.default_json, help_text='AI 요약 생성 시 사용된 메타데이터 (모델, 생성시간 등)'),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='basic_information_info',
            field=models.JSONField(blank=True, default=wiki.models.default_json, help_text='기본 정보의 메타데이터 (출처, 업데이트 시간 등)'),
        ),
    ]
