# Generated by Django 5.2.5 on 2025-08-16 09:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_popularkeyward_click_num'),
        ('wiki', '0002_alter_wikiplace_ai_summation_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(help_text='리뷰 내용')),
                ('review_score', models.DecimalField(decimal_places=2, help_text='리뷰 점수 (1-5)', max_digits=3)),
                ('review_image', models.ImageField(blank=True, help_text='리뷰 이미지', null=True, upload_to='reviews/')),
                ('session_key', models.CharField(help_text='작성자 세션 키', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='리뷰 작성 시간')),
                ('place', models.ForeignKey(help_text='리뷰가 작성된 장소', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.place')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰들',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='신고 사유', max_length=50)),
                ('report_title', models.CharField(help_text='신고 제목', max_length=100)),
                ('report_content', models.TextField(help_text='신고 내용')),
                ('session_key', models.CharField(help_text='신고자 세션 키', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='신고 시간')),
                ('review', models.ForeignKey(help_text='신고된 리뷰', on_delete=django.db.models.deletion.CASCADE, to='wiki.review')),
            ],
            options={
                'verbose_name': '신고',
                'verbose_name_plural': '신고들',
            },
        ),
    ]
