# Generated by Django 5.2.5 on 2025-08-16 14:31

import django.db.models.deletion
import django.utils.timezone
import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_popularkeyward_click_num'),
        ('wiki', '0003_review_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.review'),
        ),
        migrations.AlterField(
            model_name='report',
            name='session_key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.place'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_score',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='session_key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='ai_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='ai_summation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='ai_summation_info',
            field=models.JSONField(blank=True, default=wiki.models.default_json),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='average_review_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='basic_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='basic_information_info',
            field=models.JSONField(blank=True, default=wiki.models.default_json),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='kakao_place_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.place'),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to=wiki.models.wiki_image_upload_path),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='total_review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikiplace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wikisearchhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wikisearchhistory',
            name='search_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wikisearchhistory',
            name='search_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wikisearchhistory',
            name='search_query',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wikisearchhistory',
            name='search_type',
            field=models.CharField(choices=[('place_name', '장소명 검색'), ('location_name', '지역명 검색'), ('category', '카테고리 검색'), ('mixed', '복합 검색')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='wikisearchhistory',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
