# Generated by Django 5.2.5 on 2025-08-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_report_created_at_alter_report_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='place',
        ),
        migrations.RemoveField(
            model_name='wikiplace',
            name='place',
        ),
        migrations.RemoveField(
            model_name='wikiplace',
            name='shop_image',
        ),
        migrations.AddField(
            model_name='review',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wikiplace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
