# Generated by Django 5.2.5 on 2025-08-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_remove_review_place_remove_wikiplace_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='place_id',
        ),
        migrations.AddField(
            model_name='review',
            name='wiki_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='wiki.wikiplace'),
        ),
    ]
