# Generated by Django 5.2.5 on 2025-08-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_remove_review_place_id_review_wiki_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='wiki_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='wiki.wikiplace'),
        ),
    ]
