# Generated by Django 5.2.5 on 2025-08-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_review_wiki_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
