# Generated by Django 5.2.5 on 2025-08-19 03:39

import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_review_like_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to=wiki.models.wiki_image_upload_path),
        ),
    ]
