# Generated by Django 5.2.5 on 2025-08-16 18:47

import django.db.models.deletion
import django.utils.timezone
import taro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_popularkeyward_click_num'),
        ('taro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarocard',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='card_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to=taro.models.taro_card_image_upload_path),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='card_position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='taro.taroconversation'),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='distance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='draw_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='kakao_place_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place'),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='place_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='recommendation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarocard',
            name='road_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tarocartitem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='taro.tarocard'),
        ),
        migrations.AlterField(
            model_name='tarocartitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarocartitem',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tarocartitem',
            name='selection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarocartitem',
            name='session_key',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='card_draw_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='conversation_history',
            field=models.JSONField(default=taro.models.default_json),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='conversation_stage',
            field=models.CharField(choices=[('greeting', '인사 단계'), ('questioning', '질문 단계'), ('analyzing', '분석 단계'), ('recommending', '추천 단계'), ('completed', '완료 단계')], default='greeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='last_ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='max_card_draws',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='max_questions',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='session_key',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='user_identifier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='user_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='user_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taroconversation',
            name='user_preferences',
            field=models.JSONField(default=taro.models.default_json),
        ),
        migrations.AlterField(
            model_name='taroquestiontemplate',
            name='answer_choices',
            field=models.JSONField(default=taro.models.default_json),
        ),
        migrations.AlterField(
            model_name='taroquestiontemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taroquestiontemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='taroquestiontemplate',
            name='question_category',
            field=models.CharField(choices=[('location_preference', '위치 선호도'), ('activity_type', '활동 유형'), ('atmosphere', '분위기'), ('time_preference', '시간 선호도'), ('group_size', '그룹 크기'), ('budget', '예산'), ('weather', '날씨 관련'), ('mood', '기분/감정'), ('special_occasion', '특별한 날'), ('food_preference', '음식 선호도')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taroquestiontemplate',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taroquestiontemplate',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
